[mudkip]
title = "Sphinx + Mudkip + Codespaces = PDF"
preset = "rtd"

# this is a replacement of conf.py
[mudkip.override]
language = "ru"
myst_enable_extensions = ["replacements", "tasklist"]
latex_documents = [["index", "demo.tex", "Demo of PDF Generation", "Author A. Name", "manual"]]
[mudkip.override.latex_elements]
preamble = "\\usepackage[utf8]{inputenc}"
babel = "\\usepackage[russian,english]{babel}"
cmappkg = "\\usepackage{cmap}"
fontenc = "\\usepackage[T1,T2A]{fontenc}"
utf8extra = "DeclareUnicodeCharacter{00A0}{\\nobreakspace}"
