[mudkip]
title = "Sphinx + Mudkip + Codespaces = PDF"
preset = "rtd"

# this is a replacement of conf.py
[mudkip.override]
language = "ru"
myst_enable_extensions = ["replacements", "tasklist"]
latex_documents = [["index", "demo.tex", "Demo of PDF Generation", "Author A. Name", "manual"]]
[mudkip.override.latex_elements]
# using code from https://github.com/mazhartsev/sphinx-ru/blob/master/docs/conf.py#L186-L199
preamble = "\\usepackage[utf8]{inputenc}"
# alternative: https://tex.stackexchange.com/a/424514/175151
babel = "\\usepackage[russian,english]{babel}"
cmappkg = "\\usepackage{cmap}"
fontenc = "\\usepackage[T1,T2A]{fontenc}"
utf8extra = "\\DeclareUnicodeCharacter{00A0}{\\nobreakspace}"
